classes:
- system.linux.system.repo.docker
- system.kubernetes.pool.cluster
- system.salt.minion.cert.k8s_client
- system.salt.minion.cert.etcd_client
- cluster.virtual-mcp11-k8s-calico.infra
parameters:
  docker:
    host:
      pkgs:
        - docker-engine=1.12.6-0~ubuntu-xenial
        - python-docker
  kubernetes:
    pool:
      network:
        etcd:
          ssl:
            enabled: true
        image: calico/node:latest
        calicoctl:
          image: calico/ctl:latest
        cni:
          image: calico/cni:latest
    common:
      hyperkube:
        image: gcr.io/google_containers/hyperkube-amd64:v1.5.6
